/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { GridProps, SelectFieldProps, TextFieldProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type AdmissionsCreateFormInputValues = {
    firstName?: string;
    lastName?: string;
    expectToEnroll?: string;
    pronouns?: string;
    sex?: string;
    SSN?: number;
    address?: string;
    gender?: string;
    ethnicity?: string;
    zip?: number;
    country?: string;
    homePhone?: string;
    mobilePhone?: string;
    email?: string;
    city?: string;
    DOB?: string;
    emergencyContactRelationship?: string;
    emergencyContactPhone?: string;
    emergencyContactAddress?: string;
    emergencyContactCity?: string;
    emergencyContactState?: string;
    emergencyContactZip?: number;
    emergencyContactFirstName?: string;
    PGSFirstName?: string;
    PGSLastName?: string;
    PGSAddress?: string;
    PGSHomePhone?: string;
    emergencyContactLastName?: string;
    PGSEmail?: string;
    PGSFax?: string;
    state?: string;
    PGSSponsor?: string;
    PGSLegalCustody?: string;
    PGSPhysicalCustody?: string;
    PGSEmergencyContact?: string;
    PGSParentGuardian?: string;
    PGSRelationship?: string;
    PGSMobilePhone?: string;
    PGSWorkPhone?: string;
    PGSWorkEmail?: string;
    PGSWorkFax?: string;
    howDIdYouHearAboutCCFIL?: string;
    referralSource?: string;
    whatEventsLeadToSeekTreatment?: string;
    PGSEmployer?: string;
    applicantsStrengths?: string;
    applicantsWeaknesses?: string;
    currentPlacementLocation?: string;
    currentPlacementDates?: string;
    currentPlacementProvider?: string;
    PGSJobTitle?: string;
    psychAnger?: string;
    psychSuicidality?: string;
    psychSexualActivity?: string;
    whatGoalsReceivingTreatment?: string;
    psychLegalProblems?: string;
    medicalSurgeriesIllnessesHospitalizations?: string;
    medicalPrescriptions?: string;
    medicalVitaminsSupplements?: string;
    allergiesAsthma?: string;
    inhalerEpiPen?: string;
    inhalerType?: string;
    autoInsurance?: string;
    currentPlacementReason?: string;
    autoInsuranceClaimNumber?: string;
    psychSubstanceIssues?: string;
    autoInsuranceClaimAdjuster?: string;
    autoInsuranceAddress?: string;
    autoInsuranceCity?: string;
    autoInsuranceState?: string;
    autoInsuranceZip?: number;
    autoInsurancePhone?: string;
    workersCompInsurance?: string;
    workersCompInsuranceCarrier?: string;
    autoInsuranceDOL?: string;
    workersCompClaimAdjuster?: string;
    workersCompAddress?: string;
    autoInsuranceCarrier?: string;
    PGSContactMethod?: string;
    workersCompZip?: string;
    workersCompPhone?: string;
    workersCompClaimNumber?: string;
    workersCompCity?: string;
    workersCompState?: string;
};
export declare type AdmissionsCreateFormValidationValues = {
    firstName?: ValidationFunction<string>;
    lastName?: ValidationFunction<string>;
    expectToEnroll?: ValidationFunction<string>;
    pronouns?: ValidationFunction<string>;
    sex?: ValidationFunction<string>;
    SSN?: ValidationFunction<number>;
    address?: ValidationFunction<string>;
    gender?: ValidationFunction<string>;
    ethnicity?: ValidationFunction<string>;
    zip?: ValidationFunction<number>;
    country?: ValidationFunction<string>;
    homePhone?: ValidationFunction<string>;
    mobilePhone?: ValidationFunction<string>;
    email?: ValidationFunction<string>;
    city?: ValidationFunction<string>;
    DOB?: ValidationFunction<string>;
    emergencyContactRelationship?: ValidationFunction<string>;
    emergencyContactPhone?: ValidationFunction<string>;
    emergencyContactAddress?: ValidationFunction<string>;
    emergencyContactCity?: ValidationFunction<string>;
    emergencyContactState?: ValidationFunction<string>;
    emergencyContactZip?: ValidationFunction<number>;
    emergencyContactFirstName?: ValidationFunction<string>;
    PGSFirstName?: ValidationFunction<string>;
    PGSLastName?: ValidationFunction<string>;
    PGSAddress?: ValidationFunction<string>;
    PGSHomePhone?: ValidationFunction<string>;
    emergencyContactLastName?: ValidationFunction<string>;
    PGSEmail?: ValidationFunction<string>;
    PGSFax?: ValidationFunction<string>;
    state?: ValidationFunction<string>;
    PGSSponsor?: ValidationFunction<string>;
    PGSLegalCustody?: ValidationFunction<string>;
    PGSPhysicalCustody?: ValidationFunction<string>;
    PGSEmergencyContact?: ValidationFunction<string>;
    PGSParentGuardian?: ValidationFunction<string>;
    PGSRelationship?: ValidationFunction<string>;
    PGSMobilePhone?: ValidationFunction<string>;
    PGSWorkPhone?: ValidationFunction<string>;
    PGSWorkEmail?: ValidationFunction<string>;
    PGSWorkFax?: ValidationFunction<string>;
    howDIdYouHearAboutCCFIL?: ValidationFunction<string>;
    referralSource?: ValidationFunction<string>;
    whatEventsLeadToSeekTreatment?: ValidationFunction<string>;
    PGSEmployer?: ValidationFunction<string>;
    applicantsStrengths?: ValidationFunction<string>;
    applicantsWeaknesses?: ValidationFunction<string>;
    currentPlacementLocation?: ValidationFunction<string>;
    currentPlacementDates?: ValidationFunction<string>;
    currentPlacementProvider?: ValidationFunction<string>;
    PGSJobTitle?: ValidationFunction<string>;
    psychAnger?: ValidationFunction<string>;
    psychSuicidality?: ValidationFunction<string>;
    psychSexualActivity?: ValidationFunction<string>;
    whatGoalsReceivingTreatment?: ValidationFunction<string>;
    psychLegalProblems?: ValidationFunction<string>;
    medicalSurgeriesIllnessesHospitalizations?: ValidationFunction<string>;
    medicalPrescriptions?: ValidationFunction<string>;
    medicalVitaminsSupplements?: ValidationFunction<string>;
    allergiesAsthma?: ValidationFunction<string>;
    inhalerEpiPen?: ValidationFunction<string>;
    inhalerType?: ValidationFunction<string>;
    autoInsurance?: ValidationFunction<string>;
    currentPlacementReason?: ValidationFunction<string>;
    autoInsuranceClaimNumber?: ValidationFunction<string>;
    psychSubstanceIssues?: ValidationFunction<string>;
    autoInsuranceClaimAdjuster?: ValidationFunction<string>;
    autoInsuranceAddress?: ValidationFunction<string>;
    autoInsuranceCity?: ValidationFunction<string>;
    autoInsuranceState?: ValidationFunction<string>;
    autoInsuranceZip?: ValidationFunction<number>;
    autoInsurancePhone?: ValidationFunction<string>;
    workersCompInsurance?: ValidationFunction<string>;
    workersCompInsuranceCarrier?: ValidationFunction<string>;
    autoInsuranceDOL?: ValidationFunction<string>;
    workersCompClaimAdjuster?: ValidationFunction<string>;
    workersCompAddress?: ValidationFunction<string>;
    autoInsuranceCarrier?: ValidationFunction<string>;
    PGSContactMethod?: ValidationFunction<string>;
    workersCompZip?: ValidationFunction<string>;
    workersCompPhone?: ValidationFunction<string>;
    workersCompClaimNumber?: ValidationFunction<string>;
    workersCompCity?: ValidationFunction<string>;
    workersCompState?: ValidationFunction<string>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type AdmissionsCreateFormOverridesProps = {
    AdmissionsCreateFormGrid?: PrimitiveOverrideProps<GridProps>;
    firstName?: PrimitiveOverrideProps<TextFieldProps>;
    lastName?: PrimitiveOverrideProps<TextFieldProps>;
    expectToEnroll?: PrimitiveOverrideProps<TextFieldProps>;
    pronouns?: PrimitiveOverrideProps<SelectFieldProps>;
    sex?: PrimitiveOverrideProps<SelectFieldProps>;
    SSN?: PrimitiveOverrideProps<TextFieldProps>;
    address?: PrimitiveOverrideProps<TextFieldProps>;
    gender?: PrimitiveOverrideProps<SelectFieldProps>;
    ethnicity?: PrimitiveOverrideProps<SelectFieldProps>;
    zip?: PrimitiveOverrideProps<TextFieldProps>;
    country?: PrimitiveOverrideProps<TextFieldProps>;
    homePhone?: PrimitiveOverrideProps<TextFieldProps>;
    mobilePhone?: PrimitiveOverrideProps<TextFieldProps>;
    email?: PrimitiveOverrideProps<TextFieldProps>;
    city?: PrimitiveOverrideProps<TextFieldProps>;
    DOB?: PrimitiveOverrideProps<TextFieldProps>;
    emergencyContactRelationship?: PrimitiveOverrideProps<TextFieldProps>;
    emergencyContactPhone?: PrimitiveOverrideProps<TextFieldProps>;
    emergencyContactAddress?: PrimitiveOverrideProps<TextFieldProps>;
    emergencyContactCity?: PrimitiveOverrideProps<TextFieldProps>;
    emergencyContactState?: PrimitiveOverrideProps<SelectFieldProps>;
    emergencyContactZip?: PrimitiveOverrideProps<TextFieldProps>;
    emergencyContactFirstName?: PrimitiveOverrideProps<TextFieldProps>;
    PGSFirstName?: PrimitiveOverrideProps<TextFieldProps>;
    PGSLastName?: PrimitiveOverrideProps<TextFieldProps>;
    PGSAddress?: PrimitiveOverrideProps<TextFieldProps>;
    PGSHomePhone?: PrimitiveOverrideProps<TextFieldProps>;
    emergencyContactLastName?: PrimitiveOverrideProps<TextFieldProps>;
    PGSEmail?: PrimitiveOverrideProps<TextFieldProps>;
    PGSFax?: PrimitiveOverrideProps<TextFieldProps>;
    state?: PrimitiveOverrideProps<SelectFieldProps>;
    PGSSponsor?: PrimitiveOverrideProps<TextFieldProps>;
    PGSLegalCustody?: PrimitiveOverrideProps<TextFieldProps>;
    PGSPhysicalCustody?: PrimitiveOverrideProps<TextFieldProps>;
    PGSEmergencyContact?: PrimitiveOverrideProps<TextFieldProps>;
    PGSParentGuardian?: PrimitiveOverrideProps<TextFieldProps>;
    PGSRelationship?: PrimitiveOverrideProps<TextFieldProps>;
    PGSMobilePhone?: PrimitiveOverrideProps<TextFieldProps>;
    PGSWorkPhone?: PrimitiveOverrideProps<TextFieldProps>;
    PGSWorkEmail?: PrimitiveOverrideProps<TextFieldProps>;
    PGSWorkFax?: PrimitiveOverrideProps<TextFieldProps>;
    howDIdYouHearAboutCCFIL?: PrimitiveOverrideProps<TextFieldProps>;
    referralSource?: PrimitiveOverrideProps<TextFieldProps>;
    whatEventsLeadToSeekTreatment?: PrimitiveOverrideProps<TextFieldProps>;
    PGSEmployer?: PrimitiveOverrideProps<TextFieldProps>;
    applicantsStrengths?: PrimitiveOverrideProps<TextFieldProps>;
    applicantsWeaknesses?: PrimitiveOverrideProps<TextFieldProps>;
    currentPlacementLocation?: PrimitiveOverrideProps<TextFieldProps>;
    currentPlacementDates?: PrimitiveOverrideProps<TextFieldProps>;
    currentPlacementProvider?: PrimitiveOverrideProps<TextFieldProps>;
    PGSJobTitle?: PrimitiveOverrideProps<TextFieldProps>;
    psychAnger?: PrimitiveOverrideProps<TextFieldProps>;
    psychSuicidality?: PrimitiveOverrideProps<TextFieldProps>;
    psychSexualActivity?: PrimitiveOverrideProps<TextFieldProps>;
    whatGoalsReceivingTreatment?: PrimitiveOverrideProps<TextFieldProps>;
    psychLegalProblems?: PrimitiveOverrideProps<TextFieldProps>;
    medicalSurgeriesIllnessesHospitalizations?: PrimitiveOverrideProps<TextFieldProps>;
    medicalPrescriptions?: PrimitiveOverrideProps<TextFieldProps>;
    medicalVitaminsSupplements?: PrimitiveOverrideProps<TextFieldProps>;
    allergiesAsthma?: PrimitiveOverrideProps<TextFieldProps>;
    inhalerEpiPen?: PrimitiveOverrideProps<TextFieldProps>;
    inhalerType?: PrimitiveOverrideProps<TextFieldProps>;
    autoInsurance?: PrimitiveOverrideProps<TextFieldProps>;
    currentPlacementReason?: PrimitiveOverrideProps<TextFieldProps>;
    autoInsuranceClaimNumber?: PrimitiveOverrideProps<TextFieldProps>;
    psychSubstanceIssues?: PrimitiveOverrideProps<TextFieldProps>;
    autoInsuranceClaimAdjuster?: PrimitiveOverrideProps<TextFieldProps>;
    autoInsuranceAddress?: PrimitiveOverrideProps<TextFieldProps>;
    autoInsuranceCity?: PrimitiveOverrideProps<TextFieldProps>;
    autoInsuranceState?: PrimitiveOverrideProps<SelectFieldProps>;
    autoInsuranceZip?: PrimitiveOverrideProps<TextFieldProps>;
    autoInsurancePhone?: PrimitiveOverrideProps<TextFieldProps>;
    workersCompInsurance?: PrimitiveOverrideProps<TextFieldProps>;
    workersCompInsuranceCarrier?: PrimitiveOverrideProps<TextFieldProps>;
    autoInsuranceDOL?: PrimitiveOverrideProps<TextFieldProps>;
    workersCompClaimAdjuster?: PrimitiveOverrideProps<TextFieldProps>;
    workersCompAddress?: PrimitiveOverrideProps<TextFieldProps>;
    autoInsuranceCarrier?: PrimitiveOverrideProps<TextFieldProps>;
    PGSContactMethod?: PrimitiveOverrideProps<TextFieldProps>;
    workersCompZip?: PrimitiveOverrideProps<TextFieldProps>;
    workersCompPhone?: PrimitiveOverrideProps<TextFieldProps>;
    workersCompClaimNumber?: PrimitiveOverrideProps<TextFieldProps>;
    workersCompCity?: PrimitiveOverrideProps<TextFieldProps>;
    workersCompState?: PrimitiveOverrideProps<SelectFieldProps>;
} & EscapeHatchProps;
export declare type AdmissionsCreateFormProps = React.PropsWithChildren<{
    overrides?: AdmissionsCreateFormOverridesProps | undefined | null;
} & {
    clearOnSuccess?: boolean;
    onSubmit?: (fields: AdmissionsCreateFormInputValues) => AdmissionsCreateFormInputValues;
    onSuccess?: (fields: AdmissionsCreateFormInputValues) => void;
    onError?: (fields: AdmissionsCreateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: AdmissionsCreateFormInputValues) => AdmissionsCreateFormInputValues;
    onValidate?: AdmissionsCreateFormValidationValues;
} & React.CSSProperties>;
export default function AdmissionsCreateForm(props: AdmissionsCreateFormProps): React.ReactElement;
