// @ts-check
import { initSchema } from '@aws-amplify/datastore';
import { schema } from './schema';

const Pronouns = {
  "HEHIM": "HEHIM",
  "SHEHER": "SHEHER",
  "THEYTHEM": "THEYTHEM",
  "OTHER": "OTHER"
};

const Sex = {
  "MALE": "MALE",
  "FEMALE": "FEMALE",
  "DECLINETOANSWER": "DECLINETOANSWER"
};

const Gender = {
  "AGENDER": "AGENDER",
  "ANDROGYNE": "ANDROGYNE",
  "BIGENDER": "BIGENDER",
  "BUTCH": "BUTCH",
  "CISGENDER": "CISGENDER",
  "GENDEREXPANSIVE": "GENDEREXPANSIVE",
  "GENDERFLUID": "GENDERFLUID",
  "GENDEROUTLAW": "GENDEROUTLAW",
  "GENDERQUEER": "GENDERQUEER",
  "MASCULINEOFCENTER": "MASCULINEOFCENTER",
  "NONBINARY": "NONBINARY",
  "OMNIGENDER": "OMNIGENDER",
  "POLYGENDERANDPANGENDER": "POLYGENDERANDPANGENDER",
  "TRANSGENDER": "TRANSGENDER",
  "TRANS": "TRANS",
  "TWOSPIRIT": "TWOSPIRIT",
  "DECLINETOANSWER": "DECLINETOANSWER"
};

const Ethnicity = {
  "AFRICAN": "AFRICAN",
  "CARIBBEAN": "CARIBBEAN",
  "INDIAN": "INDIAN",
  "MELANESIAN": "MELANESIAN",
  "AUSTRALASIANABORIGINAL": "AUSTRALASIANABORIGINAL",
  "CHINESE": "CHINESE",
  "GUAMANIAN": "GUAMANIAN",
  "JAPANESE": "JAPANESE",
  "KOREAN": "KOREAN",
  "EUROPEANANGLOSAXON": "EUROPEANANGLOSAXON",
  "OTHERPACIFICISLANDER": "OTHERPACIFICISLANDER",
  "LATINAMERICAN": "LATINAMERICAN",
  "ARABIC": "ARABIC",
  "VIETNAMESE": "VIETNAMESE",
  "MICRONESIAN": "MICRONESIAN",
  "DECLINEDTORESPOND": "DECLINEDTORESPOND",
  "OTHERHISPANIC": "OTHERHISPANIC",
  "USORCANADIANINDIAN": "USORCANADIANINDIAN",
  "OTHERASIAN": "OTHERASIAN",
  "PUERTORICAN": "PUERTORICAN",
  "FILIPINO": "FILIPINO",
  "MEXICAN": "MEXICAN",
  "ALASKANNATIVE": "ALASKANNATIVE",
  "CUBAN": "CUBAN"
};

const State = {
  "ALABAMA": "ALABAMA",
  "ALASKA": "ALASKA",
  "ARIZONA": "ARIZONA",
  "ARKANSAS": "ARKANSAS",
  "AMERICANSAMOA": "AMERICANSAMOA",
  "CALIFORNIA": "CALIFORNIA",
  "COLORADO": "COLORADO",
  "CONNECTICUT": "CONNECTICUT",
  "DELAWARE": "DELAWARE",
  "DISTRICTOFCOLUMBIA": "DISTRICTOFCOLUMBIA",
  "FLORIDA": "FLORIDA",
  "GEORGIA": "GEORGIA",
  "GUAM": "GUAM",
  "HAWAII": "HAWAII",
  "IDAHO": "IDAHO",
  "ILLINOIS": "ILLINOIS",
  "INDIANA": "INDIANA",
  "IOWA": "IOWA",
  "KANSAS": "KANSAS",
  "KENTUCKY": "KENTUCKY",
  "LOUISIANA": "LOUISIANA",
  "MAINE": "MAINE",
  "MARYLAND": "MARYLAND",
  "MASSACHUSETTS": "MASSACHUSETTS",
  "MICHIGAN": "MICHIGAN",
  "MINNESOTA": "MINNESOTA",
  "MISSISSIPPI": "MISSISSIPPI",
  "MISSOURI": "MISSOURI",
  "MONTANA": "MONTANA",
  "NEBRASKA": "NEBRASKA",
  "NEVADA": "NEVADA",
  "NEWHAMPSHIRE": "NEWHAMPSHIRE",
  "NEWJERSEY": "NEWJERSEY",
  "NEWMEXICO": "NEWMEXICO",
  "NEWYORK": "NEWYORK",
  "NORTHCAROLINA": "NORTHCAROLINA",
  "NORTHDAKOTA": "NORTHDAKOTA",
  "NORTHERNMARIANAISLANDS": "NORTHERNMARIANAISLANDS",
  "OHIO": "OHIO",
  "OKLAHOMA": "OKLAHOMA",
  "OREGON": "OREGON",
  "PENNSYLVANIA": "PENNSYLVANIA",
  "PUERTORICO": "PUERTORICO",
  "RHODEISLAND": "RHODEISLAND",
  "SOUTHCAROLINA": "SOUTHCAROLINA",
  "SOUTHDAKOTA": "SOUTHDAKOTA",
  "TENNESSEE": "TENNESSEE",
  "TEXAS": "TEXAS",
  "TRUSTTERRITORIES": "TRUSTTERRITORIES",
  "UTAH": "UTAH",
  "VERMONT": "VERMONT",
  "VIRGINIA": "VIRGINIA",
  "VIRGINISLANDS": "VIRGINISLANDS",
  "WASHINGTON": "WASHINGTON",
  "WESTVIRGINIA": "WESTVIRGINIA",
  "WISCONSIN": "WISCONSIN",
  "WYOMING": "WYOMING"
};

const { Admissions, Referrals, Icon, Services, TeamMember, Headshot, InsuranceOrderType, MedicalInsurance, MedicalHistory } = initSchema(schema);

export {
  Admissions,
  Referrals,
  Icon,
  Services,
  TeamMember,
  Headshot,
  Pronouns,
  Sex,
  Gender,
  Ethnicity,
  State,
  InsuranceOrderType,
  MedicalInsurance,
  MedicalHistory
};