/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

import * as APITypes from "./API";
type GeneratedSubscription<InputType, OutputType> = string & {
  __generatedSubscriptionInput: InputType;
  __generatedSubscriptionOutput: OutputType;
};

export const onCreateAdmissions = /* GraphQL */ `subscription OnCreateAdmissions(
  $filter: ModelSubscriptionAdmissionsFilterInput
) {
  onCreateAdmissions(filter: $filter) {
    id
    firstName
    lastName
    expectToEnroll
    pronouns
    sex
    SSN
    address
    gender
    ethnicity
    zip
    country
    homePhone
    mobilePhone
    email
    city
    DOB
    emergencyContactRelationship
    emergencyContactPhone
    emergencyContactAddress
    emergencyContactCity
    emergencyContactState
    emergencyContactZip
    emergencyContactFirstName
    PGSFirstName
    PGSLastName
    PGSAddress
    PGSHomePhone
    emergencyContactLastName
    PGSEmail
    PGSFax
    state
    PGSSponsor
    PGSLegalCustody
    PGSPhysicalCustody
    PGSEmergencyContact
    PGSParentGuardian
    PGSRelationship
    PGSMobilePhone
    PGSWorkPhone
    PGSWorkEmail
    PGSWorkFax
    howDIdYouHearAboutCCFIL
    referralSource
    whatEventsLeadToSeekTreatment
    PGSEmployer
    applicantsStrengths
    applicantsWeaknesses
    currentPlacementLocation
    currentPlacementDates
    currentPlacementProvider
    PGSJobTitle
    psychAnger
    psychSuicidality
    psychSexualActivity
    whatGoalsReceivingTreatment
    psychLegalProblems
    medicalSurgeriesIllnessesHospitalizations
    medicalPrescriptions
    medicalVitaminsSupplements
    medicalHistory {
      allergies
      anaphylacticShock
      anemia
      ankleProblem
      anorexiaBulimia
      appendicitis
      armProblem
      arthritis
      asthma
      backProblems
      bedwetting
      bladderKidneyProblems
      bleedingDisorder
      boneCondition
      bowelProblems
      brokenBones
      cancer
      chestPains
      chronicCough
      circulationIssues
      coldsFrequent
      constipation
      cystsTumors
      dermatitis
      diabetes
      diarrhea
      difficultyWalking
      earInfections
      endocrineProblems
      excessiveSweating
      faintingDizziness
      heartDisease
      footProblem
      frequentColdsSoreThroats
      frequentHeartburn
      frequentMuscleCramps
      frequentShortnessOfBreath
      frostbite
      gasBloating
      HIVAIDS
      headTraumas
      headachesMigraines
      hearingImpairment
      heartProblemsMurmurs
      hepatitisABC
      hernia
      highBloodPressure
      hypoglycemia
      intoleranceToCold
      intoleranceToHeat
      irregularHeartbeat
      jointInjuries
      kidneyProblems
      kneeProblem
      legProblem
      liverProblems
      lungInfections
      medicalEquipmentDevices
      meningitis
      menstrualProblems
      mononucleosis
      motionSickness
      obesity
      other
      PMSSevereSymptoms
      pneumoniaBronchitis
      pregnancy
      recurrentInjurySurgery
      STDs
      scoliosis
      seizuresEpilepsy
      shoulderProblem
      skinDiseasesProblems
      sleepwalking
      TBPositive
      TBRecentExposure
      tuberculosis
      thyroidProblems
      ulcers
      unexpectedWeightLoss
      urinationProblem
      __typename
    }
    allergiesAsthma
    inhalerEpiPen
    inhalerType
    autoInsurance
    currentPlacementReason
    autoInsuranceClaimNumber
    psychSubstanceIssues
    autoInsuranceClaimAdjuster
    autoInsuranceAddress
    autoInsuranceCity
    autoInsuranceState
    autoInsuranceZip
    autoInsurancePhone
    workersCompInsurance
    workersCompInsuranceCarrier
    autoInsuranceDOL
    workersCompClaimAdjuster
    workersCompAddress
    autoInsuranceCarrier
    PGSContactMethod
    workersCompZip
    workersCompPhone
    medicalInsurance {
      companyName
      address
      phone
      groupNumber
      policyNumber
      policyholdersFirstName
      policyholdersLastName
      employer
      DOB
      SSN
      orderType {
        primary
        secondary
        __typename
      }
      __typename
    }
    workersCompClaimNumber
    workersCompCity
    workersCompState
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateAdmissionsSubscriptionVariables,
  APITypes.OnCreateAdmissionsSubscription
>;
export const onUpdateAdmissions = /* GraphQL */ `subscription OnUpdateAdmissions(
  $filter: ModelSubscriptionAdmissionsFilterInput
) {
  onUpdateAdmissions(filter: $filter) {
    id
    firstName
    lastName
    expectToEnroll
    pronouns
    sex
    SSN
    address
    gender
    ethnicity
    zip
    country
    homePhone
    mobilePhone
    email
    city
    DOB
    emergencyContactRelationship
    emergencyContactPhone
    emergencyContactAddress
    emergencyContactCity
    emergencyContactState
    emergencyContactZip
    emergencyContactFirstName
    PGSFirstName
    PGSLastName
    PGSAddress
    PGSHomePhone
    emergencyContactLastName
    PGSEmail
    PGSFax
    state
    PGSSponsor
    PGSLegalCustody
    PGSPhysicalCustody
    PGSEmergencyContact
    PGSParentGuardian
    PGSRelationship
    PGSMobilePhone
    PGSWorkPhone
    PGSWorkEmail
    PGSWorkFax
    howDIdYouHearAboutCCFIL
    referralSource
    whatEventsLeadToSeekTreatment
    PGSEmployer
    applicantsStrengths
    applicantsWeaknesses
    currentPlacementLocation
    currentPlacementDates
    currentPlacementProvider
    PGSJobTitle
    psychAnger
    psychSuicidality
    psychSexualActivity
    whatGoalsReceivingTreatment
    psychLegalProblems
    medicalSurgeriesIllnessesHospitalizations
    medicalPrescriptions
    medicalVitaminsSupplements
    medicalHistory {
      allergies
      anaphylacticShock
      anemia
      ankleProblem
      anorexiaBulimia
      appendicitis
      armProblem
      arthritis
      asthma
      backProblems
      bedwetting
      bladderKidneyProblems
      bleedingDisorder
      boneCondition
      bowelProblems
      brokenBones
      cancer
      chestPains
      chronicCough
      circulationIssues
      coldsFrequent
      constipation
      cystsTumors
      dermatitis
      diabetes
      diarrhea
      difficultyWalking
      earInfections
      endocrineProblems
      excessiveSweating
      faintingDizziness
      heartDisease
      footProblem
      frequentColdsSoreThroats
      frequentHeartburn
      frequentMuscleCramps
      frequentShortnessOfBreath
      frostbite
      gasBloating
      HIVAIDS
      headTraumas
      headachesMigraines
      hearingImpairment
      heartProblemsMurmurs
      hepatitisABC
      hernia
      highBloodPressure
      hypoglycemia
      intoleranceToCold
      intoleranceToHeat
      irregularHeartbeat
      jointInjuries
      kidneyProblems
      kneeProblem
      legProblem
      liverProblems
      lungInfections
      medicalEquipmentDevices
      meningitis
      menstrualProblems
      mononucleosis
      motionSickness
      obesity
      other
      PMSSevereSymptoms
      pneumoniaBronchitis
      pregnancy
      recurrentInjurySurgery
      STDs
      scoliosis
      seizuresEpilepsy
      shoulderProblem
      skinDiseasesProblems
      sleepwalking
      TBPositive
      TBRecentExposure
      tuberculosis
      thyroidProblems
      ulcers
      unexpectedWeightLoss
      urinationProblem
      __typename
    }
    allergiesAsthma
    inhalerEpiPen
    inhalerType
    autoInsurance
    currentPlacementReason
    autoInsuranceClaimNumber
    psychSubstanceIssues
    autoInsuranceClaimAdjuster
    autoInsuranceAddress
    autoInsuranceCity
    autoInsuranceState
    autoInsuranceZip
    autoInsurancePhone
    workersCompInsurance
    workersCompInsuranceCarrier
    autoInsuranceDOL
    workersCompClaimAdjuster
    workersCompAddress
    autoInsuranceCarrier
    PGSContactMethod
    workersCompZip
    workersCompPhone
    medicalInsurance {
      companyName
      address
      phone
      groupNumber
      policyNumber
      policyholdersFirstName
      policyholdersLastName
      employer
      DOB
      SSN
      orderType {
        primary
        secondary
        __typename
      }
      __typename
    }
    workersCompClaimNumber
    workersCompCity
    workersCompState
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateAdmissionsSubscriptionVariables,
  APITypes.OnUpdateAdmissionsSubscription
>;
export const onDeleteAdmissions = /* GraphQL */ `subscription OnDeleteAdmissions(
  $filter: ModelSubscriptionAdmissionsFilterInput
) {
  onDeleteAdmissions(filter: $filter) {
    id
    firstName
    lastName
    expectToEnroll
    pronouns
    sex
    SSN
    address
    gender
    ethnicity
    zip
    country
    homePhone
    mobilePhone
    email
    city
    DOB
    emergencyContactRelationship
    emergencyContactPhone
    emergencyContactAddress
    emergencyContactCity
    emergencyContactState
    emergencyContactZip
    emergencyContactFirstName
    PGSFirstName
    PGSLastName
    PGSAddress
    PGSHomePhone
    emergencyContactLastName
    PGSEmail
    PGSFax
    state
    PGSSponsor
    PGSLegalCustody
    PGSPhysicalCustody
    PGSEmergencyContact
    PGSParentGuardian
    PGSRelationship
    PGSMobilePhone
    PGSWorkPhone
    PGSWorkEmail
    PGSWorkFax
    howDIdYouHearAboutCCFIL
    referralSource
    whatEventsLeadToSeekTreatment
    PGSEmployer
    applicantsStrengths
    applicantsWeaknesses
    currentPlacementLocation
    currentPlacementDates
    currentPlacementProvider
    PGSJobTitle
    psychAnger
    psychSuicidality
    psychSexualActivity
    whatGoalsReceivingTreatment
    psychLegalProblems
    medicalSurgeriesIllnessesHospitalizations
    medicalPrescriptions
    medicalVitaminsSupplements
    medicalHistory {
      allergies
      anaphylacticShock
      anemia
      ankleProblem
      anorexiaBulimia
      appendicitis
      armProblem
      arthritis
      asthma
      backProblems
      bedwetting
      bladderKidneyProblems
      bleedingDisorder
      boneCondition
      bowelProblems
      brokenBones
      cancer
      chestPains
      chronicCough
      circulationIssues
      coldsFrequent
      constipation
      cystsTumors
      dermatitis
      diabetes
      diarrhea
      difficultyWalking
      earInfections
      endocrineProblems
      excessiveSweating
      faintingDizziness
      heartDisease
      footProblem
      frequentColdsSoreThroats
      frequentHeartburn
      frequentMuscleCramps
      frequentShortnessOfBreath
      frostbite
      gasBloating
      HIVAIDS
      headTraumas
      headachesMigraines
      hearingImpairment
      heartProblemsMurmurs
      hepatitisABC
      hernia
      highBloodPressure
      hypoglycemia
      intoleranceToCold
      intoleranceToHeat
      irregularHeartbeat
      jointInjuries
      kidneyProblems
      kneeProblem
      legProblem
      liverProblems
      lungInfections
      medicalEquipmentDevices
      meningitis
      menstrualProblems
      mononucleosis
      motionSickness
      obesity
      other
      PMSSevereSymptoms
      pneumoniaBronchitis
      pregnancy
      recurrentInjurySurgery
      STDs
      scoliosis
      seizuresEpilepsy
      shoulderProblem
      skinDiseasesProblems
      sleepwalking
      TBPositive
      TBRecentExposure
      tuberculosis
      thyroidProblems
      ulcers
      unexpectedWeightLoss
      urinationProblem
      __typename
    }
    allergiesAsthma
    inhalerEpiPen
    inhalerType
    autoInsurance
    currentPlacementReason
    autoInsuranceClaimNumber
    psychSubstanceIssues
    autoInsuranceClaimAdjuster
    autoInsuranceAddress
    autoInsuranceCity
    autoInsuranceState
    autoInsuranceZip
    autoInsurancePhone
    workersCompInsurance
    workersCompInsuranceCarrier
    autoInsuranceDOL
    workersCompClaimAdjuster
    workersCompAddress
    autoInsuranceCarrier
    PGSContactMethod
    workersCompZip
    workersCompPhone
    medicalInsurance {
      companyName
      address
      phone
      groupNumber
      policyNumber
      policyholdersFirstName
      policyholdersLastName
      employer
      DOB
      SSN
      orderType {
        primary
        secondary
        __typename
      }
      __typename
    }
    workersCompClaimNumber
    workersCompCity
    workersCompState
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteAdmissionsSubscriptionVariables,
  APITypes.OnDeleteAdmissionsSubscription
>;
export const onCreateReferrals = /* GraphQL */ `subscription OnCreateReferrals($filter: ModelSubscriptionReferralsFilterInput) {
  onCreateReferrals(filter: $filter) {
    id
    date
    source
    name
    followUp
    DOA
    DOADate
    reasonForDecline
    howDidYouHearAboutUs
    assistanceProvided
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateReferralsSubscriptionVariables,
  APITypes.OnCreateReferralsSubscription
>;
export const onUpdateReferrals = /* GraphQL */ `subscription OnUpdateReferrals($filter: ModelSubscriptionReferralsFilterInput) {
  onUpdateReferrals(filter: $filter) {
    id
    date
    source
    name
    followUp
    DOA
    DOADate
    reasonForDecline
    howDidYouHearAboutUs
    assistanceProvided
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateReferralsSubscriptionVariables,
  APITypes.OnUpdateReferralsSubscription
>;
export const onDeleteReferrals = /* GraphQL */ `subscription OnDeleteReferrals($filter: ModelSubscriptionReferralsFilterInput) {
  onDeleteReferrals(filter: $filter) {
    id
    date
    source
    name
    followUp
    DOA
    DOADate
    reasonForDecline
    howDidYouHearAboutUs
    assistanceProvided
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteReferralsSubscriptionVariables,
  APITypes.OnDeleteReferralsSubscription
>;
export const onCreateIcon = /* GraphQL */ `subscription OnCreateIcon($filter: ModelSubscriptionIconFilterInput) {
  onCreateIcon(filter: $filter) {
    id
    alt
    src
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateIconSubscriptionVariables,
  APITypes.OnCreateIconSubscription
>;
export const onUpdateIcon = /* GraphQL */ `subscription OnUpdateIcon($filter: ModelSubscriptionIconFilterInput) {
  onUpdateIcon(filter: $filter) {
    id
    alt
    src
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateIconSubscriptionVariables,
  APITypes.OnUpdateIconSubscription
>;
export const onDeleteIcon = /* GraphQL */ `subscription OnDeleteIcon($filter: ModelSubscriptionIconFilterInput) {
  onDeleteIcon(filter: $filter) {
    id
    alt
    src
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteIconSubscriptionVariables,
  APITypes.OnDeleteIconSubscription
>;
export const onCreateServices = /* GraphQL */ `subscription OnCreateServices($filter: ModelSubscriptionServicesFilterInput) {
  onCreateServices(filter: $filter) {
    id
    serviceTitle
    serviceBodyText
    Icon {
      id
      alt
      src
      createdAt
      updatedAt
      __typename
    }
    createdAt
    updatedAt
    servicesIconId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateServicesSubscriptionVariables,
  APITypes.OnCreateServicesSubscription
>;
export const onUpdateServices = /* GraphQL */ `subscription OnUpdateServices($filter: ModelSubscriptionServicesFilterInput) {
  onUpdateServices(filter: $filter) {
    id
    serviceTitle
    serviceBodyText
    Icon {
      id
      alt
      src
      createdAt
      updatedAt
      __typename
    }
    createdAt
    updatedAt
    servicesIconId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateServicesSubscriptionVariables,
  APITypes.OnUpdateServicesSubscription
>;
export const onDeleteServices = /* GraphQL */ `subscription OnDeleteServices($filter: ModelSubscriptionServicesFilterInput) {
  onDeleteServices(filter: $filter) {
    id
    serviceTitle
    serviceBodyText
    Icon {
      id
      alt
      src
      createdAt
      updatedAt
      __typename
    }
    createdAt
    updatedAt
    servicesIconId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteServicesSubscriptionVariables,
  APITypes.OnDeleteServicesSubscription
>;
export const onCreateTeamMember = /* GraphQL */ `subscription OnCreateTeamMember(
  $filter: ModelSubscriptionTeamMemberFilterInput
) {
  onCreateTeamMember(filter: $filter) {
    id
    firstName
    lastName
    bio
    link
    title
    isFeatured
    Image {
      id
      src
      alt
      imageTitle
      createdAt
      updatedAt
      __typename
    }
    isLeader
    userId
    createdAt
    updatedAt
    teamMemberImageId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateTeamMemberSubscriptionVariables,
  APITypes.OnCreateTeamMemberSubscription
>;
export const onUpdateTeamMember = /* GraphQL */ `subscription OnUpdateTeamMember(
  $filter: ModelSubscriptionTeamMemberFilterInput
) {
  onUpdateTeamMember(filter: $filter) {
    id
    firstName
    lastName
    bio
    link
    title
    isFeatured
    Image {
      id
      src
      alt
      imageTitle
      createdAt
      updatedAt
      __typename
    }
    isLeader
    userId
    createdAt
    updatedAt
    teamMemberImageId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateTeamMemberSubscriptionVariables,
  APITypes.OnUpdateTeamMemberSubscription
>;
export const onDeleteTeamMember = /* GraphQL */ `subscription OnDeleteTeamMember(
  $filter: ModelSubscriptionTeamMemberFilterInput
) {
  onDeleteTeamMember(filter: $filter) {
    id
    firstName
    lastName
    bio
    link
    title
    isFeatured
    Image {
      id
      src
      alt
      imageTitle
      createdAt
      updatedAt
      __typename
    }
    isLeader
    userId
    createdAt
    updatedAt
    teamMemberImageId
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteTeamMemberSubscriptionVariables,
  APITypes.OnDeleteTeamMemberSubscription
>;
export const onCreateHeadshot = /* GraphQL */ `subscription OnCreateHeadshot($filter: ModelSubscriptionHeadshotFilterInput) {
  onCreateHeadshot(filter: $filter) {
    id
    src
    alt
    imageTitle
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnCreateHeadshotSubscriptionVariables,
  APITypes.OnCreateHeadshotSubscription
>;
export const onUpdateHeadshot = /* GraphQL */ `subscription OnUpdateHeadshot($filter: ModelSubscriptionHeadshotFilterInput) {
  onUpdateHeadshot(filter: $filter) {
    id
    src
    alt
    imageTitle
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnUpdateHeadshotSubscriptionVariables,
  APITypes.OnUpdateHeadshotSubscription
>;
export const onDeleteHeadshot = /* GraphQL */ `subscription OnDeleteHeadshot($filter: ModelSubscriptionHeadshotFilterInput) {
  onDeleteHeadshot(filter: $filter) {
    id
    src
    alt
    imageTitle
    createdAt
    updatedAt
    __typename
  }
}
` as GeneratedSubscription<
  APITypes.OnDeleteHeadshotSubscriptionVariables,
  APITypes.OnDeleteHeadshotSubscription
>;
