export const accordionData = [
    {id: `accordion1`,accordionTitle: `COMPREHENSIVE ASSESSMENT UPON ADMISSION`, accordionBodyText: `Upon admission, each resident is evaluated by our occupational therapists through formal assessments, observations, and interviews to establish performance within the areas of activities of daily living, memory and attention, social adjustment, and safety.`, icon: `ICON1`},
    {id: `accordion2`,accordionTitle: `OCCUPATIONAL THERAPY SERVICES`, accordionBodyText: `Our occupational therapy services are the foundation of all our programming — from the initial assessment of each resident through — the continuous monitoring of their program goals and objectives. All residents receive therapy routinely and on a scheduled basis. Our occupational therapists also facilitate our peer support groups and our supported employment program.`, icon: `ICON1`},
    {id: `accordion3`,accordionTitle: `INDIVIDUALIZED REHABILITATION PLANS`, accordionBodyText: `CCFIL individualized rehabilitation plans and programming are developed through our one-to-one occupational therapy services which are offered to each resident. Each resident is provided with a lead occupational therapist to establish and oversee programming goals and objectives unique to meeting their needs. We provide licensed nursing staff to assist our residents with medication management as well as support services for any medical issues that may require assistance.`, icon: `ICON1`},
    {id: `accordion4`,accordionTitle: `RESIDENT SPECIFIC SUPERVISION`, accordionBodyText: `We respect the autonomy and personal space of our residents. Each resident is assessed individually upon admission to determine the supervision required that allows them to live in the least restrictive environment possible. We have found this approach gives our residents the best opportunity for optimal progression in their rehabilitation toward independence.`, icon: `ICON1`},
    {id: `accordion5`,accordionTitle: `FAMILY SUPPORT SERVICES`, accordionBodyText: `Our family support services welcome our residents’ family members' involvement in their rehabilitation. We are distinctive in accepting spouses and children of residents into our program. Additionally, we have a child development specialist on staff. Our child development specialist has proven to be invaluable in providing parenting in-services, exploring community family resources, and assisting in appropriate school placement of our residents’ children.`, icon: `ICON1`},
    {id: `accordion6`,accordionTitle: `EDUCATIONAL/GED TUTORIAL SERVICES`, accordionBodyText: `As many of our residents’ progress in their rehabilitation, going back to school to complete a high school diploma or a college degree becomes a realistic goal. Our educational support staff — made up of certified special education and general education teachers — assist in making those educational goals achievable through our one-to-one tutorial services.`, icon: `ICON1`},
    {id: `accordion7`,accordionTitle: `PEER SUPPORT GROUPS`, accordionBodyText: `Although our supported independent living program is occupational therapy centered and clinically based, we provide our residents the chance to meet with other residents to share their experiences and support one another. This opportunity has given our residents a valuable therapeutic venue to further facilitate a successful rehabilitation. Our peer support groups include a Men’s Club, Women’s Club, Walking Club, Iron Chef Club, CC Cares and various community outings.`, icon: `ICON1`},
    {id: `accordion8`,accordionTitle: `RECREATIONAL OUTINGS & COMMUNITY SOCIAL OPPORTUNITIES`, 
    accordionBodyText: `We offer recreational outings and community social opportunities to help our residents improve their prosocial skills and to have fun interacting with their community at the same time. All the activities selected are suggested and chosen by our residents. This aligns with our program philosophy of being choice-driven and respectful of each person’s autonomy.
    Previous outings and social opportunities have included
    - Going to Tigers Games
     - Going Fishing
     - Getting Manicures & Pedicures
     - Doing a Karaoke Night
     - Going to Concerts
     - Going to Canterbury Village
     - Going to Greenfield Village
     - Going to Museums
     - Going to the Detroit & Toledo Zoos`, icon: `ICON1`},
    {id: `accordion9`,accordionTitle: `TRANSPORTATION`, accordionBodyText: `Transportation is a component of our program that is not to be undervalued. It is more than transporting our residents from place to place. It is really a time to build trusting relationships through listening and respectful dialogue. Our transportation is provided by all our staff members with our own fleet of vehicles`, icon: `ICON1`}
]