'use client';
import * as React from "react";
import { GridProps, SwitchFieldProps } from "@aws-amplify/ui-react";
import { MedicalHistory } from "../../utils/graphql/API.ts";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type MedicalHistoryUpdateFormInputValues = {
    allergies?: boolean;
    anaphylacticShock?: boolean;
    anemia?: boolean;
    ankleProblem?: boolean;
    anorexiaBulimia?: boolean;
    appendicitis?: boolean;
    armProblem?: boolean;
    arthritis?: boolean;
    asthma?: boolean;
    backProblems?: boolean;
    bedwetting?: boolean;
    bladderKidneyProblems?: boolean;
    bleedingDisorder?: boolean;
    boneCondition?: boolean;
    bowelProblems?: boolean;
    brokenBones?: boolean;
    cancer?: boolean;
    chestPains?: boolean;
    chronicCough?: boolean;
    circulationIssues?: boolean;
    coldsFrequent?: boolean;
    constipation?: boolean;
    cystsTumors?: boolean;
    dermatitis?: boolean;
    diabetes?: boolean;
    diarrhea?: boolean;
    difficultyWalking?: boolean;
    earInfections?: boolean;
    endocrineProblems?: boolean;
    excessiveSweating?: boolean;
    faintingDizziness?: boolean;
    heartDisease?: boolean;
    footProblem?: boolean;
    frequentColdsSoreThroats?: boolean;
    frequentHeartburn?: boolean;
    frequentMuscleCramps?: boolean;
    frequentShortnessOfBreath?: boolean;
    frostbite?: boolean;
    gasBloating?: boolean;
    HIVAIDS?: boolean;
    headTraumas?: boolean;
    headachesMigraines?: boolean;
    hearingImpairment?: boolean;
    heartProblemsMurmurs?: boolean;
    hepatitisABC?: boolean;
    hernia?: boolean;
    highBloodPressure?: boolean;
    hypoglycemia?: boolean;
    intoleranceToCold?: boolean;
    intoleranceToHeat?: boolean;
    irregularHeartbeat?: boolean;
    jointInjuries?: boolean;
    kidneyProblems?: boolean;
    kneeProblem?: boolean;
    legProblem?: boolean;
    liverProblems?: boolean;
    lungInfections?: boolean;
    medicalEquipmentDevices?: boolean;
    meningitis?: boolean;
    menstrualProblems?: boolean;
    mononucleosis?: boolean;
    motionSickness?: boolean;
    obesity?: boolean;
    other?: boolean;
    PMSSevereSymptoms?: boolean;
    pneumoniaBronchitis?: boolean;
    pregnancy?: boolean;
    recurrentInjurySurgery?: boolean;
    STDs?: boolean;
    scoliosis?: boolean;
    seizuresEpilepsy?: boolean;
    shoulderProblem?: boolean;
    skinDiseasesProblems?: boolean;
    sleepwalking?: boolean;
    TBPositive?: boolean;
    TBRecentExposure?: boolean;
    tuberculosis?: boolean;
    thyroidProblems?: boolean;
    ulcers?: boolean;
    unexpectedWeightLoss?: boolean;
    urinationProblem?: boolean;
};
export declare type MedicalHistoryUpdateFormValidationValues = {
    allergies?: ValidationFunction<boolean>;
    anaphylacticShock?: ValidationFunction<boolean>;
    anemia?: ValidationFunction<boolean>;
    ankleProblem?: ValidationFunction<boolean>;
    anorexiaBulimia?: ValidationFunction<boolean>;
    appendicitis?: ValidationFunction<boolean>;
    armProblem?: ValidationFunction<boolean>;
    arthritis?: ValidationFunction<boolean>;
    asthma?: ValidationFunction<boolean>;
    backProblems?: ValidationFunction<boolean>;
    bedwetting?: ValidationFunction<boolean>;
    bladderKidneyProblems?: ValidationFunction<boolean>;
    bleedingDisorder?: ValidationFunction<boolean>;
    boneCondition?: ValidationFunction<boolean>;
    bowelProblems?: ValidationFunction<boolean>;
    brokenBones?: ValidationFunction<boolean>;
    cancer?: ValidationFunction<boolean>;
    chestPains?: ValidationFunction<boolean>;
    chronicCough?: ValidationFunction<boolean>;
    circulationIssues?: ValidationFunction<boolean>;
    coldsFrequent?: ValidationFunction<boolean>;
    constipation?: ValidationFunction<boolean>;
    cystsTumors?: ValidationFunction<boolean>;
    dermatitis?: ValidationFunction<boolean>;
    diabetes?: ValidationFunction<boolean>;
    diarrhea?: ValidationFunction<boolean>;
    difficultyWalking?: ValidationFunction<boolean>;
    earInfections?: ValidationFunction<boolean>;
    endocrineProblems?: ValidationFunction<boolean>;
    excessiveSweating?: ValidationFunction<boolean>;
    faintingDizziness?: ValidationFunction<boolean>;
    heartDisease?: ValidationFunction<boolean>;
    footProblem?: ValidationFunction<boolean>;
    frequentColdsSoreThroats?: ValidationFunction<boolean>;
    frequentHeartburn?: ValidationFunction<boolean>;
    frequentMuscleCramps?: ValidationFunction<boolean>;
    frequentShortnessOfBreath?: ValidationFunction<boolean>;
    frostbite?: ValidationFunction<boolean>;
    gasBloating?: ValidationFunction<boolean>;
    HIVAIDS?: ValidationFunction<boolean>;
    headTraumas?: ValidationFunction<boolean>;
    headachesMigraines?: ValidationFunction<boolean>;
    hearingImpairment?: ValidationFunction<boolean>;
    heartProblemsMurmurs?: ValidationFunction<boolean>;
    hepatitisABC?: ValidationFunction<boolean>;
    hernia?: ValidationFunction<boolean>;
    highBloodPressure?: ValidationFunction<boolean>;
    hypoglycemia?: ValidationFunction<boolean>;
    intoleranceToCold?: ValidationFunction<boolean>;
    intoleranceToHeat?: ValidationFunction<boolean>;
    irregularHeartbeat?: ValidationFunction<boolean>;
    jointInjuries?: ValidationFunction<boolean>;
    kidneyProblems?: ValidationFunction<boolean>;
    kneeProblem?: ValidationFunction<boolean>;
    legProblem?: ValidationFunction<boolean>;
    liverProblems?: ValidationFunction<boolean>;
    lungInfections?: ValidationFunction<boolean>;
    medicalEquipmentDevices?: ValidationFunction<boolean>;
    meningitis?: ValidationFunction<boolean>;
    menstrualProblems?: ValidationFunction<boolean>;
    mononucleosis?: ValidationFunction<boolean>;
    motionSickness?: ValidationFunction<boolean>;
    obesity?: ValidationFunction<boolean>;
    other?: ValidationFunction<boolean>;
    PMSSevereSymptoms?: ValidationFunction<boolean>;
    pneumoniaBronchitis?: ValidationFunction<boolean>;
    pregnancy?: ValidationFunction<boolean>;
    recurrentInjurySurgery?: ValidationFunction<boolean>;
    STDs?: ValidationFunction<boolean>;
    scoliosis?: ValidationFunction<boolean>;
    seizuresEpilepsy?: ValidationFunction<boolean>;
    shoulderProblem?: ValidationFunction<boolean>;
    skinDiseasesProblems?: ValidationFunction<boolean>;
    sleepwalking?: ValidationFunction<boolean>;
    TBPositive?: ValidationFunction<boolean>;
    TBRecentExposure?: ValidationFunction<boolean>;
    tuberculosis?: ValidationFunction<boolean>;
    thyroidProblems?: ValidationFunction<boolean>;
    ulcers?: ValidationFunction<boolean>;
    unexpectedWeightLoss?: ValidationFunction<boolean>;
    urinationProblem?: ValidationFunction<boolean>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type MedicalHistoryUpdateFormOverridesProps = {
    MedicalHistoryUpdateFormGrid?: PrimitiveOverrideProps<GridProps>;
    allergies?: PrimitiveOverrideProps<SwitchFieldProps>;
    anaphylacticShock?: PrimitiveOverrideProps<SwitchFieldProps>;
    anemia?: PrimitiveOverrideProps<SwitchFieldProps>;
    ankleProblem?: PrimitiveOverrideProps<SwitchFieldProps>;
    anorexiaBulimia?: PrimitiveOverrideProps<SwitchFieldProps>;
    appendicitis?: PrimitiveOverrideProps<SwitchFieldProps>;
    armProblem?: PrimitiveOverrideProps<SwitchFieldProps>;
    arthritis?: PrimitiveOverrideProps<SwitchFieldProps>;
    asthma?: PrimitiveOverrideProps<SwitchFieldProps>;
    backProblems?: PrimitiveOverrideProps<SwitchFieldProps>;
    bedwetting?: PrimitiveOverrideProps<SwitchFieldProps>;
    bladderKidneyProblems?: PrimitiveOverrideProps<SwitchFieldProps>;
    bleedingDisorder?: PrimitiveOverrideProps<SwitchFieldProps>;
    boneCondition?: PrimitiveOverrideProps<SwitchFieldProps>;
    bowelProblems?: PrimitiveOverrideProps<SwitchFieldProps>;
    brokenBones?: PrimitiveOverrideProps<SwitchFieldProps>;
    cancer?: PrimitiveOverrideProps<SwitchFieldProps>;
    chestPains?: PrimitiveOverrideProps<SwitchFieldProps>;
    chronicCough?: PrimitiveOverrideProps<SwitchFieldProps>;
    circulationIssues?: PrimitiveOverrideProps<SwitchFieldProps>;
    coldsFrequent?: PrimitiveOverrideProps<SwitchFieldProps>;
    constipation?: PrimitiveOverrideProps<SwitchFieldProps>;
    cystsTumors?: PrimitiveOverrideProps<SwitchFieldProps>;
    dermatitis?: PrimitiveOverrideProps<SwitchFieldProps>;
    diabetes?: PrimitiveOverrideProps<SwitchFieldProps>;
    diarrhea?: PrimitiveOverrideProps<SwitchFieldProps>;
    difficultyWalking?: PrimitiveOverrideProps<SwitchFieldProps>;
    earInfections?: PrimitiveOverrideProps<SwitchFieldProps>;
    endocrineProblems?: PrimitiveOverrideProps<SwitchFieldProps>;
    excessiveSweating?: PrimitiveOverrideProps<SwitchFieldProps>;
    faintingDizziness?: PrimitiveOverrideProps<SwitchFieldProps>;
    heartDisease?: PrimitiveOverrideProps<SwitchFieldProps>;
    footProblem?: PrimitiveOverrideProps<SwitchFieldProps>;
    frequentColdsSoreThroats?: PrimitiveOverrideProps<SwitchFieldProps>;
    frequentHeartburn?: PrimitiveOverrideProps<SwitchFieldProps>;
    frequentMuscleCramps?: PrimitiveOverrideProps<SwitchFieldProps>;
    frequentShortnessOfBreath?: PrimitiveOverrideProps<SwitchFieldProps>;
    frostbite?: PrimitiveOverrideProps<SwitchFieldProps>;
    gasBloating?: PrimitiveOverrideProps<SwitchFieldProps>;
    HIVAIDS?: PrimitiveOverrideProps<SwitchFieldProps>;
    headTraumas?: PrimitiveOverrideProps<SwitchFieldProps>;
    headachesMigraines?: PrimitiveOverrideProps<SwitchFieldProps>;
    hearingImpairment?: PrimitiveOverrideProps<SwitchFieldProps>;
    heartProblemsMurmurs?: PrimitiveOverrideProps<SwitchFieldProps>;
    hepatitisABC?: PrimitiveOverrideProps<SwitchFieldProps>;
    hernia?: PrimitiveOverrideProps<SwitchFieldProps>;
    highBloodPressure?: PrimitiveOverrideProps<SwitchFieldProps>;
    hypoglycemia?: PrimitiveOverrideProps<SwitchFieldProps>;
    intoleranceToCold?: PrimitiveOverrideProps<SwitchFieldProps>;
    intoleranceToHeat?: PrimitiveOverrideProps<SwitchFieldProps>;
    irregularHeartbeat?: PrimitiveOverrideProps<SwitchFieldProps>;
    jointInjuries?: PrimitiveOverrideProps<SwitchFieldProps>;
    kidneyProblems?: PrimitiveOverrideProps<SwitchFieldProps>;
    kneeProblem?: PrimitiveOverrideProps<SwitchFieldProps>;
    legProblem?: PrimitiveOverrideProps<SwitchFieldProps>;
    liverProblems?: PrimitiveOverrideProps<SwitchFieldProps>;
    lungInfections?: PrimitiveOverrideProps<SwitchFieldProps>;
    medicalEquipmentDevices?: PrimitiveOverrideProps<SwitchFieldProps>;
    meningitis?: PrimitiveOverrideProps<SwitchFieldProps>;
    menstrualProblems?: PrimitiveOverrideProps<SwitchFieldProps>;
    mononucleosis?: PrimitiveOverrideProps<SwitchFieldProps>;
    motionSickness?: PrimitiveOverrideProps<SwitchFieldProps>;
    obesity?: PrimitiveOverrideProps<SwitchFieldProps>;
    other?: PrimitiveOverrideProps<SwitchFieldProps>;
    PMSSevereSymptoms?: PrimitiveOverrideProps<SwitchFieldProps>;
    pneumoniaBronchitis?: PrimitiveOverrideProps<SwitchFieldProps>;
    pregnancy?: PrimitiveOverrideProps<SwitchFieldProps>;
    recurrentInjurySurgery?: PrimitiveOverrideProps<SwitchFieldProps>;
    STDs?: PrimitiveOverrideProps<SwitchFieldProps>;
    scoliosis?: PrimitiveOverrideProps<SwitchFieldProps>;
    seizuresEpilepsy?: PrimitiveOverrideProps<SwitchFieldProps>;
    shoulderProblem?: PrimitiveOverrideProps<SwitchFieldProps>;
    skinDiseasesProblems?: PrimitiveOverrideProps<SwitchFieldProps>;
    sleepwalking?: PrimitiveOverrideProps<SwitchFieldProps>;
    TBPositive?: PrimitiveOverrideProps<SwitchFieldProps>;
    TBRecentExposure?: PrimitiveOverrideProps<SwitchFieldProps>;
    tuberculosis?: PrimitiveOverrideProps<SwitchFieldProps>;
    thyroidProblems?: PrimitiveOverrideProps<SwitchFieldProps>;
    ulcers?: PrimitiveOverrideProps<SwitchFieldProps>;
    unexpectedWeightLoss?: PrimitiveOverrideProps<SwitchFieldProps>;
    urinationProblem?: PrimitiveOverrideProps<SwitchFieldProps>;
} & EscapeHatchProps;
export declare type MedicalHistoryUpdateFormProps = React.PropsWithChildren<{
    overrides?: MedicalHistoryUpdateFormOverridesProps | undefined | null;
} & {
    id?: string;
    medicalHistory?: MedicalHistory;
    onSubmit?: (fields: MedicalHistoryUpdateFormInputValues) => MedicalHistoryUpdateFormInputValues;
    onSuccess?: (fields: MedicalHistoryUpdateFormInputValues) => void;
    onError?: (fields: MedicalHistoryUpdateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: MedicalHistoryUpdateFormInputValues) => MedicalHistoryUpdateFormInputValues;
    onValidate?: MedicalHistoryUpdateFormValidationValues;
} & React.CSSProperties>;
export default function MedicalHistoryUpdateForm(props: MedicalHistoryUpdateFormProps): React.ReactElement;
